### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by PanXF-HUST** [unlock-music/cli#13]
下载了对应系统版本的release版本（Windows x64，下载的是um-windows-amd64），运行exe文件弹出命令行就闪退，不知道原因在哪里，想请问一下如何解决啊

**Comment by Darius-H** [comment]
看说明
![image](https://user-images.githubusercontent.com/49788663/124391575-d4e05e80-dd23-11eb-9afb-e9c85bf64411.png)
