### ISSUE TITLE
32bit位深度hires音频解密后为24bit

### ISSUE THREAD

**Issue by ClariceFang** [unlock-music/cli#15]
从Viper HIFI下载的32bit 96k的.vpr格式的音频文件，解密之后变成24bit 96k
应该是解密后格式为flac的原因 如果是wav应该就没有问题了
实例文件：https://www.aliyundrive.com/s/fU9fRvTxihr

![image](https://user-images.githubusercontent.com/88266733/127763142-aa88f465-b35f-4bb5-9ccd-eef18b26e457.png)

**Comment by ix64** [comment]
这和我们的unlock-music项目没有一丝一毫的关系，请联系音频的提供方。

----------

该邮件从移动设备发送





--------------原始邮件--------------
发件人："ClariceFang ***@***.***&gt;;
发送时间：2021年8月1日(星期天) 下午3:37
收件人："unlock-music/cli" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[unlock-music/cli] 32bit位深度hires音频解密后为24bit (#15)
-----------------------------------

 

 
从Viper HIFI下载的32bit 96k的.vpr格式的音频文件，解密之后变成24bit 96k
 应该是解密后格式为flac的原因 如果是wav应该就没有问题了
 实例文件：https://www.aliyundrive.com/s/fU9fRvTxihr

**Comment by ClariceFang** [comment]
> 这和我们的unlock-music项目没有一丝一毫的关系，请联系音频的提供方。
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："ClariceFang ***@***.***&gt;; 发送时间：2021年8月1日(星期天) 下午3:37 收件人："unlock-music/cli" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：[unlock-music/cli] 32bit位深度hires音频解密后为24bit (#15) ----------------------------------- 从Viper HIFI下载的32bit 96k的.vpr格式的音频文件，解密之后变成24bit 96k 应该是解密后格式为flac的原因 如果是wav应该就没有问题了 实例文件：https://www.aliyundrive.com/s/fU9fRvTxihr — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我的意思是 解密后的格式能是wav嘛 这样就可以解决这个问题

**Comment by ix64** [comment]
不能，此项目“照原样”将数据进行解密。而解密出的数据仅由加密者决定
