### ISSUE TITLE
package embed is not in GOROOT

### ISSUE THREAD

**Issue by aihy** [unlock-music/cli#2]
algo/kgm/mask.go:5:2: package embed is not in GOROOT (/usr/local/Cellar/go/1.15.6/libexec/src/embed)

in macOS Big Sur 11.1

**Comment by aihy** [comment]
I see, it needs go 1.16

**Comment by emmmx** [comment]
> I see, it needs go 1.16

Yeah, This project is using the new feature from the unreleased version golang 1.16 (it's beta now). Without this, the `.kgm` decryption will not works.
