### ISSUE TITLE
增加 mggl 格式的处理

### ISSUE THREAD

**Issue by zjns** [unlock-music/cli#25]
不知道是 `mggl` 和 `mgg1` 格式都存在，还是开发搞错了，Mac版QQ音乐下载下来的加密文件会存在 `mggl` 格式，我改源码编译试了下，能够解密成功，解出来是 `ogg` 格式，能够播放。
样本：[Taylor Swift-All Too Well (Explicit|Sad Girl Autumn Version|Recorded at Long Pond Studios)](https://c.y.qq.com/base/fcgi-bin/u?__=kGm4Y5O54j3m) 标准音质

**Comment by mikoto11** [comment]
我这里还有mgg0的
