### ISSUE TITLE
批量转换失败

### ISSUE THREAD

**Issue by Pastechn** [unlock-music/cli#8]
在使用 CLI 版本进行批量转换时会转换失败，而使用 JS 版则可以成功转换。
使用场景：Windows 平台，在 um.exe 同目录下建立了两个文件夹，一个 input，一个 output，使用 um -i input -o output 后出现错误提示：
```
2021/02/27 20:53:44.011 [33mWARN[0m   try decode failed
2021/02/27 20:53:44.019 [31mERROR[0m  conversion failed       {"source": "01.qmcflac"}
2021/02/27 20:53:44.031 [33mWARN[0m   try decode failed
2021/02/27 20:53:44.032 [31mERROR[0m  conversion failed       {"source": "02.qmcflac"}
2021/02/27 20:53:44.044 [33mWARN[0m   try decode failed
2021/02/27 20:53:44.045 [31mERROR[0m  conversion failed       {"source": "03.qmcflac"}
2021/02/27 20:53:44.050 [33mWARN[0m   try decode failed
2021/02/27 20:53:44.050 [31mERROR[0m  conversion failed       {"source": "04.qmcflac"}
```

**Comment by ix64** [comment]
你好，请提供样本文件

----------

该邮件从移动设备发送




--------------原始邮件--------------
发件人："Pastechn "<notifications@github.com&gt;;
发送时间：2021年2月27日(星期六) 晚上9:00
收件人："unlock-music/cli" <cli@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[unlock-music/cli] 批量转换失败 (#8)
-----------------------------------

 

 
在使用 CLI 版本进行批量转换时会转换失败，而使用 JS 版则可以成功转换。
 使用场景：Windows 平台，在 um.exe 同目录下建立了两个文件夹，一个 input，一个 output，使用 um -i input -o output 后出现错误提示：
 2021/02/27 20:53:44.011  [33mWARN [0m   try decode failed 2021/02/27 20:53:44.019  [31mERROR [0m  conversion failed       {"source": "01.qmcflac"} 2021/02/27 20:53:44.031  [33mWARN [0m   try decode failed 2021/02/27 20:53:44.032  [31mERROR [0m  conversion failed       {"source": "02.qmcflac"} 2021/02/27 20:53:44.044  [33mWARN [0m   try decode failed 2021/02/27 20:53:44.045  [31mERROR [0m  conversion failed       {"source": "03.qmcflac"} 2021/02/27 20:53:44.050  [33mWARN [0m   try decode failed 2021/02/27 20:53:44.050  [31mERROR [0m  conversion failed       {"source": "04.qmcflac"}

**Comment by Pastechn** [comment]
样本文件：https://cowtransfer.com/s/f5001ee080224b
