### ISSUE TITLE
[feature]增加对文件格式的识别

### ISSUE THREAD

**Issue by wrc1993** [unlock-music/cli#9]
现在解密后统一修改成了mp3格式，但是一般需要解密的都是flac或dff格式
希望后期可以增加。

**Comment by emmmx** [comment]
目前应该都是支持的，自动识别的格式。
如果出现哪个格式的支持问题，请提供相关信息以及样本文件。

**Comment by emmmx** [comment]
solved by c1c43d2a41b8b1b6bf308e9013d9eeab385725e7
